import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { barlowCondensed, bellefair } from "./fonts/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlowCondensed.className} antialiased`}
      >
        <div className="relative w-full">
        <Header />
        {children}
        </div>
      </body>
    </html>
  );
}
