import type { Metadata } from "next";
import "./globals.css";
import { barlowCondensed } from "./fonts/font";
import { PagesWrapper } from "@/components/PagesWrapper";

export const metadata: Metadata = {
  title: "Space Tour",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlowCondensed.className} antialiased`}
      >
        <PagesWrapper>
          {children}
        </PagesWrapper>
      </body>
    </html>
  );
}
